### ISSUE TITLE
paste.py

### ISSUE THREAD

**Issue by Yan-Xiaomin** [Xinglab/rMATS-STAT#3]
Dear professors：
   I met some questions when I run the rmats.py. The  version of  the rMATS is 'rMATS.4.0.2'.  when I run the rmats.py, it would  have some errors about "Traceback (most recent call last):
  File "/panfs/sugon/home/yanxm/softwares/rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rMATS_P/paste.py", line 52, in <module>   main()
  File "/panfs/sugon/home/yanxm/softwares/rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rMATS_P/paste.py", line 45, in main  ofp1.write(line[0]+'\n')
TypeError: 'map' object is not subscriptable". I have tried many times, however ,still unsolved. I hope you can hep me out. I really don't know the reason. I am looking forward to your  reply.

**Comment by sunnyfanyy** [comment]
I also have the same problem...

**Comment by sunnyfanyy** [comment]
> Dear professors：
> I met some questions when I run the rmats.py. The version of the rMATS is 'rMATS.4.0.2'. when I run the rmats.py, it would have some errors about "Traceback (most recent call last):
> File "/panfs/sugon/home/yanxm/softwares/rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rMATS_P/paste.py", line 52, in main()
> File "/panfs/sugon/home/yanxm/softwares/rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rMATS_P/paste.py", line 45, in main ofp1.write(line[0]+'\n')
> TypeError: 'map' object is not subscriptable". I have tried many times, however ,still unsolved. I hope you can hep me out. I really don't know the reason. I am looking forward to your reply.

I solved this problem: 
$ vi  /yourdir/rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rMATS_P/paste.py
then change `line = map(str, line)` into ` line = list(map(str, line))`

**Comment by yanxm-123** [comment]
> > Dear professors：
> > I met some questions when I run the rmats.py. The version of the rMATS is 'rMATS.4.0.2'. when I run the rmats.py, it would have some errors about "Traceback (most recent call last):
> > File "/panfs/sugon/home/yanxm/softwares/rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rMATS_P/paste.py", line 52, in main()
> > File "/panfs/sugon/home/yanxm/softwares/rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rMATS_P/paste.py", line 45, in main ofp1.write(line[0]+'\n')
> > TypeError: 'map' object is not subscriptable". I have tried many times, however ,still unsolved. I hope you can hep me out. I really don't know the reason. I am looking forward to your reply.
> 
> I solved this problem:
> $ vi /yourdir/rMATS.4.0.2/rMATS-turbo-Linux-UCS4/rMATS_P/paste.py
> then change `line = map(str, line)` into ` line = list(map(str, line))`

Thank you for your solution~
